### PR TITLE
nanox support and zemu tests

### PR DESCRIPTION
**Pull request by gupadhyaya**
nanox support and zemu tests

### CODE REVIEW

**Comment by miroslav-kubik** [comment]
> nanox support and zemu tests

Hi any ETA for Nano X support? Thank you

**Comment by JellyBean86** [comment]
I'm keen to know too please.

**Comment by tvarsis** [comment]
Why can't this be merged if it has been completed for several months? We need the Nano X support please.

**Comment by fhoxh** [comment]
@bigspider Is there an ETA on when this can be released? Many Ledger Nano X users have been anticipating using the Harmony app on Ledger Nano X. The app is **required** for staking.

**Comment by bigspider** [comment]
@fhoxh please follow up with people from Product; I don't have influence on the roadmap.

**Comment by fhoxh** [comment]
> @fhoxh please follow up with people from Product; I don't have influence on the roadmap.

Will do. Would you be able to suggest a contact please? Thank you.

**Comment by KurtisPapple** [comment]
When release? 🥣

**Pull request merged**
